"""Initial

Revision ID: 21576eccbf20
Revises: 
Create Date: 2022-07-12 04:27:12.982165

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21576eccbf20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_transactions',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('document', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('first_company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('following_names', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_surname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_surname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('country_commercial_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_personal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_commercial_id', name='unq_user_country_commercial_id'),
    sa.UniqueConstraint('country_personal_id', name='unq_user_country_personal_id')
    )
    op.create_table('accounts',
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manager_user', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('country_personal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_commercial_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_company', sa.Boolean(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('min_amount', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['manager_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('user_password_change_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('burned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_number'], ['accounts.number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_accounts')
    op.drop_table('user_password_change_requests')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('accounts_transactions')
    # ### end Alembic commands ###
